-- Services page content in all 5 languages (cs, sk, en, uk, ru)

INSERT INTO `page_t` (`page_id`, `lang_code`, `title`, `body`, `meta_title`, `meta_desc`) VALUES
  ((SELECT `id` FROM `pages` WHERE `slug` = 'services'), 'cs', 'Naše služby',
    '<div class="services-grid"><div class="service-card"><h2>Narozeninové oslavy</h2><p>Balónková výzdoba pro narozeninové oslavy všech věkových kategorií. Oblouky, girlandy, dekorovaný stůl a personalizovaný nápis přesně podle vašich přání.</p><ul><li>Balónkový oblouk nebo girlanda</li><li>Dekorovaný narozeninový stůl</li><li>Fóliová čísla a narozeninový nápis</li><li>Fotokoutek na přání</li></ul><p class="price"><strong>od 890 Kč</strong></p></div><div class="service-card"><h2>Svatební výzdoba</h2><p>Organické oblouky, romantické stropní instalace a dekorovaný sál pro nezapomenutelný svatební den.</p><ul><li>Vstupní nebo oltářní oblouk</li><li>Stropní balónková instalace</li><li>Dekorace stolů a recepce</li><li>Barvy a styl zcela na přání</li></ul><p class="price"><strong>od 1 890 Kč</strong></p></div><div class="service-card"><h2>Dětské party</h2><p>Pohádkové tematické dekorace pro nejmenší oslavence. Jednorožci, superhrdinové, princezny nebo oblíbené pohádkové postavy.</p><ul><li>Tematická výzdoba dle přání dítěte</li><li>Balónkový oblouk a girlandy</li><li>Dekorovaný dortový stůl</li><li>Balónky jako dárky pro děti</li></ul><p class="price"><strong>od 1 190 Kč</strong></p></div><div class="service-card"><h2>Firemní akce</h2><p>Profesionální výzdoba v barvách vaší firmy pro konference, veletrhy a firemní večírky. Možnost tisku loga na balónky.</p><ul><li>Vstupní oblouk v barvách firmy</li><li>Výzdoba pódia a přednáškového prostoru</li><li>Dekorace stolů a cateringu</li><li>Potisk loga na balónky (příplatek)</li></ul><p class="price"><strong>od 990 Kč</strong></p></div><div class="service-card"><h2>Baby shower a křtiny</h2><p>Jemné pastelové dekorace pro přivítání nového přírůstku do rodiny. Možnost gender reveal instalace.</p><ul><li>Pastelová balónková výzdoba</li><li>Gender reveal instalace na přání</li><li>Dekorovaný uvítací stůl</li><li>Nápis se jménem miminka</li></ul><p class="price"><strong>od 1 290 Kč</strong></p></div><div class="service-card"><h2>Maturita a promoce</h2><p>Oslavte úspěch vašich absolventů s radostnou výzdobou. Balónky ve školních barvách a oblouk pro slavnostní fotografii.</p><ul><li>Balónkový oblouk pro společné foto</li><li>Fóliové číslice ročníku ukončení</li><li>Girlandy a dekorační prvky</li><li>Barvy dle přání školy nebo třídy</li></ul><p class="price"><strong>od 890 Kč</strong></p></div></div>',
    'Balónkové dekorace na míru | BalonkyDecor',
    'Nabízíme balónkové dekorace pro narozeniny, svatby, dětské party, firemní akce i baby shower. Individuální přístup, Praha a okolí.'),

  ((SELECT `id` FROM `pages` WHERE `slug` = 'services'), 'sk', 'Naše služby',
    '<div class="services-grid"><div class="service-card"><h2>Narodeninové oslavy</h2><p>Balónová výzdoba pre narodeninové oslavy všetkých vekových kategórií. Oblúky, girlandy, ozdobený stôl a personalizovaný nápis presne podľa vašich prianí.</p><ul><li>Balónový oblúk alebo girlanda</li><li>Ozdobený narodeninový stôl</li><li>Fóliové čísla a narodeninový nápis</li><li>Fotokútik na prianie</li></ul><p class="price"><strong>od 890 Kč</strong></p></div><div class="service-card"><h2>Svadobná výzdoba</h2><p>Organické oblúky, romantické stropné inštalácie a ozdobená sála pre nezabudnuteľný svadobný deň.</p><ul><li>Vstupný alebo oltárny oblúk</li><li>Stropná balónová inštalácia</li><li>Dekorácia stolov a recepcie</li><li>Farby a štýl celkom na prianie</li></ul><p class="price"><strong>od 1 890 Kč</strong></p></div><div class="service-card"><h2>Detské párty</h2><p>Rozprávkové tematické dekorácie pre najmenších oslavencov. Jednorožci, superhrdinovia, princezné alebo obľúbené rozprávkové postavičky.</p><ul><li>Tematická výzdoba podľa priania dieťaťa</li><li>Balónový oblúk a girlandy</li><li>Ozdobený tortový stôl</li><li>Balóny ako darčeky pre deti</li></ul><p class="price"><strong>od 1 190 Kč</strong></p></div><div class="service-card"><h2>Firemné akcie</h2><p>Profesionálna výzdoba v farbách vašej firmy pre konferencie, veľtrhy a firemné večierky. Možnosť tlače loga na balóny.</p><ul><li>Vstupný oblúk v farbách firmy</li><li>Výzdoba pódia a prednáškového priestoru</li><li>Dekorácia stolov a cateringu</li><li>Potlač loga na balóny (príplatok)</li></ul><p class="price"><strong>od 990 Kč</strong></p></div><div class="service-card"><h2>Baby shower a krstiny</h2><p>Jemné pastelové dekorácie pre privítanie nového prírastku do rodiny. Možnosť gender reveal inštalácie.</p><ul><li>Pastelová balónová výzdoba</li><li>Gender reveal inštalácia na prianie</li><li>Ozdobený uvítací stôl</li><li>Nápis s menom bábätka</li></ul><p class="price"><strong>od 1 290 Kč</strong></p></div><div class="service-card"><h2>Maturita a promócie</h2><p>Oslávte úspech vašich absolventov s radostnou výzdobou. Balóny v školských farbách a oblúk pre slávnostné foto.</p><ul><li>Balónový oblúk pre spoločné foto</li><li>Fóliové číslice ročníka ukončenia</li><li>Girlandy a dekoratívne prvky</li><li>Farby podľa priania školy alebo triedy</li></ul><p class="price"><strong>od 890 Kč</strong></p></div></div>',
    'Balónové dekorácie na mieru | BalonkyDecor',
    'Ponúkame balónové dekorácie pre narodeniny, svadby, detské párty, firemné akcie aj baby shower. Individuálny prístup, Praha a okolie.'),

  ((SELECT `id` FROM `pages` WHERE `slug` = 'services'), 'en', 'Our Services',
    '<div class="services-grid"><div class="service-card"><h2>Birthday Celebrations</h2><p>Balloon decoration for birthday parties of all ages. Arches, garlands, decorated tables and personalised signs exactly to your wishes.</p><ul><li>Balloon arch or garland</li><li>Decorated birthday table</li><li>Foil number balloons and birthday sign</li><li>Photo corner on request</li></ul><p class="price"><strong>from 890 CZK</strong></p></div><div class="service-card"><h2>Wedding Decoration</h2><p>Organic arches, romantic ceiling installations and a decorated hall for an unforgettable wedding day.</p><ul><li>Entrance or altar arch</li><li>Balloon ceiling installation</li><li>Table and reception decoration</li><li>Colours and style to your taste</li></ul><p class="price"><strong>from 1,890 CZK</strong></p></div><div class="service-card"><h2>Kids Parties</h2><p>Magical themed decorations for the little ones. Unicorns, superheroes, princesses or favourite fairy-tale characters.</p><ul><li>Themed decoration of your choice</li><li>Balloon arch and garlands</li><li>Decorated cake table</li><li>Take-away balloons for children</li></ul><p class="price"><strong>from 1,190 CZK</strong></p></div><div class="service-card"><h2>Corporate Events</h2><p>Professional decoration in your company colours for conferences, trade fairs and corporate parties. Logo printing on balloons available.</p><ul><li>Entrance arch in company colours</li><li>Stage and lecture area decoration</li><li>Table and catering decoration</li><li>Logo printing on balloons (surcharge)</li></ul><p class="price"><strong>from 990 CZK</strong></p></div><div class="service-card"><h2>Baby Shower &amp; Christening</h2><p>Soft pastel decorations for welcoming a new family member. Gender reveal installation available on request.</p><ul><li>Pastel balloon decoration</li><li>Gender reveal installation on request</li><li>Decorated welcome table</li><li>Sign with the baby name</li></ul><p class="price"><strong>from 1,290 CZK</strong></p></div><div class="service-card"><h2>Graduation Celebrations</h2><p>Celebrate your graduates in style. Balloons in school colours and an arch for the ceremonial group photo.</p><ul><li>Balloon arch for group photo</li><li>Foil graduation year numbers</li><li>Garlands and decorative elements</li><li>Colours to match school or class</li></ul><p class="price"><strong>from 890 CZK</strong></p></div></div>',
    'Custom Balloon Decorations | BalonkyDecor',
    'We offer balloon decorations for birthdays, weddings, kids parties, corporate events and baby showers. Personal approach, Prague and surroundings.'),

  ((SELECT `id` FROM `pages` WHERE `slug` = 'services'), 'uk', 'Наші послуги',
    '<div class="services-grid"><div class="service-card"><h2>Святкування днів народження</h2><p>Кулькове оформлення для днів народження будь-якого віку. Арки, гірлянди, прикрашений стіл та персоналізований напис за вашим бажанням.</p><ul><li>Арка або гірлянда з кульок</li><li>Прикрашений святковий стіл</li><li>Фольговані цифри та напис</li><li>Фотозона за бажанням</li></ul><p class="price"><strong>від 890 Kč</strong></p></div><div class="service-card"><h2>Весільне оформлення</h2><p>Органічні арки, романтичні стельові інсталяції та прикрашена зала для незабутнього весільного дня.</p><ul><li>Вхідна або вівтарна арка</li><li>Стельова кулькова інсталяція</li><li>Декорація столів та рецепції</li><li>Кольори та стиль за вашим смаком</li></ul><p class="price"><strong>від 1 890 Kč</strong></p></div><div class="service-card"><h2>Дитячі свята</h2><p>Казкові тематичні декорації для найменших іменинників. Єдинороги, супергерої, принцеси або улюблені казкові персонажі.</p><ul><li>Тематичне оформлення за бажанням дитини</li><li>Арка та гірлянди з кульок</li><li>Прикрашений стіл для торта</li><li>Кульки як подарунки для дітей</li></ul><p class="price"><strong>від 1 190 Kč</strong></p></div><div class="service-card"><h2>Корпоративні заходи</h2><p>Професійне оформлення в кольорах вашої компанії для конференцій, ярмарків та корпоративів. Можливість друку логотипу на кульках.</p><ul><li>Вхідна арка в кольорах компанії</li><li>Оформлення сцени та лекційного простору</li><li>Декорація столів та кейтерингу</li><li>Друк логотипу на кульках (доплата)</li></ul><p class="price"><strong>від 990 Kč</strong></p></div><div class="service-card"><h2>Baby shower та хрестини</h2><p>Ніжні пастельні декорації для привітання нового члена родини. Можлива інсталяція gender reveal.</p><ul><li>Пастельне кулькове оформлення</li><li>Інсталяція gender reveal за бажанням</li><li>Прикрашений привітальний стіл</li><li>Напис з іменем малюка</li></ul><p class="price"><strong>від 1 290 Kč</strong></p></div><div class="service-card"><h2>Випускні та вручення дипломів</h2><p>Відсвяткуйте успіх ваших випускників з радісним оформленням. Кульки в кольорах школи та арка для урочистого фото.</p><ul><li>Арка з кульок для групового фото</li><li>Фольговані цифри випускного року</li><li>Гірлянди та декоративні елементи</li><li>Кольори за бажанням школи або класу</li></ul><p class="price"><strong>від 890 Kč</strong></p></div></div>',
    'Кулькові декорації на замовлення | BalonkyDecor',
    'Пропонуємо кулькові декорації для днів народження, весіль, дитячих свят, корпоративів та baby shower. Індивідуальний підхід, Прага та околиці.'),

  ((SELECT `id` FROM `pages` WHERE `slug` = 'services'), 'ru', 'Наши услуги',
    '<div class="services-grid"><div class="service-card"><h2>Праздники дней рождения</h2><p>Оформление шарами для дней рождения любого возраста. Арки, гирлянды, украшенный стол и персонализированная надпись по вашему желанию.</p><ul><li>Арка или гирлянда из шаров</li><li>Украшенный праздничный стол</li><li>Фольгированные цифры и надпись</li><li>Фотозона по желанию</li></ul><p class="price"><strong>от 890 Kč</strong></p></div><div class="service-card"><h2>Свадебное оформление</h2><p>Органические арки, романтические потолочные инсталляции и украшенный зал для незабываемого свадебного дня.</p><ul><li>Входная или алтарная арка</li><li>Потолочная инсталляция из шаров</li><li>Декорация столов и рецепции</li><li>Цвета и стиль по вашему вкусу</li></ul><p class="price"><strong>от 1 890 Kč</strong></p></div><div class="service-card"><h2>Детские праздники</h2><p>Сказочные тематические декорации для маленьких именинников. Единороги, супергерои, принцессы или любимые сказочные персонажи.</p><ul><li>Тематическое оформление по желанию ребёнка</li><li>Арка и гирлянды из шаров</li><li>Украшенный стол для торта</li><li>Шары в подарок детям</li></ul><p class="price"><strong>от 1 190 Kč</strong></p></div><div class="service-card"><h2>Корпоративные мероприятия</h2><p>Профессиональное оформление в цветах вашей компании для конференций, выставок и корпоративов. Возможна печать логотипа на шарах.</p><ul><li>Входная арка в цветах компании</li><li>Оформление сцены и лекционного пространства</li><li>Декорация столов и кейтеринга</li><li>Печать логотипа на шарах (доплата)</li></ul><p class="price"><strong>от 990 Kč</strong></p></div><div class="service-card"><h2>Baby shower и крестины</h2><p>Нежные пастельные декорации для встречи нового члена семьи. Возможна инсталляция gender reveal.</p><ul><li>Пастельное оформление из шаров</li><li>Инсталляция gender reveal по желанию</li><li>Украшенный приветственный стол</li><li>Надпись с именем малыша</li></ul><p class="price"><strong>от 1 290 Kč</strong></p></div><div class="service-card"><h2>Выпускные и вручение дипломов</h2><p>Отметьте успех ваших выпускников с радостным оформлением. Шары в цветах школы и арка для торжественного фото.</p><ul><li>Арка из шаров для группового фото</li><li>Фольгированные цифры выпускного года</li><li>Гирлянды и декоративные элементы</li><li>Цвета по желанию школы или класса</li></ul><p class="price"><strong>от 890 Kč</strong></p></div></div>',
    'Оформление шарами на заказ | BalonkyDecor',
    'Предлагаем оформление шарами для дней рождения, свадеб, детских праздников, корпоративов и baby shower. Индивидуальный подход, Прага и окрестности.')

ON DUPLICATE KEY UPDATE
  `title`      = VALUES(`title`),
  `body`       = VALUES(`body`),
  `meta_title` = VALUES(`meta_title`),
  `meta_desc`  = VALUES(`meta_desc`);
